server:
  port: 8081
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles.http.server.requests: "0.5, 0.9, 0.95, 0.99"
  endpoints:
    web:
      exposure:
        include: 'env,prometheus,info,health'
redis:
  port: 6379
  host: localhost

